@host=http://localhost:3100
@id = c5O7tMsGoRKP2oy8u7w56

###

POST {{host}}/products   
Content-Type: application/json
productOwner: testing

{
    "name":"Funko",
    "description":"Americano",
    "category":"Test description",
    "price":29,
    "stock":5
}


###

GET {{host}}/products

###
//////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////
GET {{host}}/users

###
POST {{host}}/users
Content-Type: application/json

{
    "name": "Lupe gomez",
    "email":"lupita@test.com",
    "username": "Lalupe32",
    "password" : "epepe"
}

###

PUT {{host}}/users/{{id}}
Content-Type: application/json

{
    "name": "Jaime el duende 2.0",
    "email":"JaimeDuene@test.com",
    "username": "Jaime Duende de Jesus Rodriguez",
    "password" : "password"
}
###
DELETE {{host}}/users/{{id}}
x-user: myAdminToken

###
