@host=http://localhost:3100
@id = c5O7tMsGoRKP2oy8u7w56

###

POST {{host}}/products   
Content-Type: application/json
productOwner: testing

{
 
    "name":"Test para video",
    "description":"Juguete",
    "category":"Test description2",
    "price":2900,
    "stock":2

}
###

GET {{host}}/products?max=300&min=100

###

GET {{host}}/products

###
DELETE {{host}}/products/X58A3gwas6ZPX9cKY2NP5

###

PUT {{host}}/products/6264c4c1c4104d11a58c49f4
Content-Type: application/json

{
 
    "name":"Nuevo Funko 3.0",
    "description":"Nuevo pubto 2.0",
    "category":"Juguetillos",
    "price":290,
    "stock":25

  
}

###
////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////


GET {{host}}/users

###
GET {{host}}/users/DVE34KeKHT9rD7NGoEM7H

###

GET {{host}}/login
password:asdasdasds
username:Thebejarano

###

POST {{host}}/users
Content-Type: application/json

 {
    "name": "Frailejon Hernesto Perez 2",
    "username": "FrailejonHP2",
    "email": "frailejon2@test.com",
    "password": "Cuidar el Awa"
  }

###

  PUT {{host}}/users/DVE34KeKHT9rD7NGoEM7H
Content-Type: application/json

 {
    "name": "Ternure628",
    "username": "ternure428lacuerpa",
    "email": "frailejon2@test.com",
    "password": "NuevoPassword"
  }

###

DELETE {{host}}/users/DVE34KeKHT9rD7NGoEM7H